### ISSUE TITLE
i have some problem with data processing

### ISSUE THREAD

**Issue by bonbonx01** [szzexpoi/POEM#2]
1. the code your provide `extract_vqa.py` and `extract_gqa.py` ,Are they used to save the data features from the .tsv file as 'image_id.npz'?" .

2. And i found in the extract_gqa.py line 32，it should be `np.save(os.path.join(args.output,'features',str(img_id)),cur_data)`  ,original code
is 'feature' ,it should be 'features'.

**Comment by szzexpoi** [comment]
For your information,
(1) You are right that the two scripts are used for processing the (big) tsv file into a collection of npy files for different images. 
(2) I do not know which "original code" you are referring to,  but it is basically for saving data into a folder with a name of your choice. I chose to use "feature" instead of "features" for simplicity, as you can see in line 88 of "gqa_exp/DataLoader.py"

Let me know if you have any other questions.

**Comment by bonbonx01** [comment]
Thank you for your patience. I do have a problem again.
The `extract_vqa.py` you provide seems to only store the bounding box information for the images in the TSV file. 
When I run "proto_learning/main.py" and setting parameter `img_dir` to the .npz file path, the `img` shape of the input model was (128,36,4), which did not match the `img_size` (which is 2048) of the Prototype_Module.
So I guess the issue is with the extract_vqa.py file.
![image](https://github.com/szzexpoi/POEM/assets/128836715/b0678bf3-9f4e-48df-bcbd-8df9e3b7c47f)

**Comment by szzexpoi** [comment]
I see, sorry for the confusion. Just double-checked the code. It appears that, for VQA and VQA-CP, I was using the h5 file generated from XNM (I only used npy for GQA experiments). You can follow the instructions here to produce the h5 file for image features (item 6):
https://github.com/shijx12/XNM-Net/tree/master/exp_vqa

**Comment by bonbonx01** [comment]
I appreciate your reply. 
Perhaps you could consider updating the class `Batch_generator_prototype_VQA` for loading vqa image features in  `proto_learning/dataloader.py` , if it's convenient for you.
Much appreciated!

**Comment by szzexpoi** [comment]
I see. For prototype learning on VQA, I did use the extracted bottom-up features, since those are extracted in older projects. I adjust the extract_vqa script so you can use it for feature extraction. For VQA task training, I used h5 file as shown in the corresponding dataloader script. I also provided the pretrained prototypes, in case you do not want to train them on your own.

**Comment by bonbonx01** [comment]
I see. You made that very clear. Thank you so much!!!
I'll close the issue.
